# Generated by Django 5.2.17 on 2026-08-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Accès actif'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text="Éditeur de l'application : crée et active les entreprises clientes.", verbose_name='Admin plateforme'),
        ),
    ]
