# Generated by Django 5.2.17 on 2026-08-30 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=40, verbose_name='N°')),
                ('kind', models.CharField(choices=[('sale', 'Vente'), ('purchase', 'Achat')], default='sale', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Validée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='parties.customer')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.organisation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.store')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='parties.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.article')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organisation', 'number'), name='uniq_org_invoice_number'),
        ),
    ]
