# Generated by Django 5.2.17 on 2026-08-30 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organisation_is_active_user_is_platform_admin'),
        ('invoicing', '0002_alter_invoice_status_payment'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_uuid',
            field=models.CharField(blank=True, db_index=True, help_text='UUID généré sur la caisse pour éviter les doublons à la synchro.', max_length=64, verbose_name='Identifiant hors-ligne'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid', ''), _negated=True), fields=('organisation', 'client_uuid'), name='uniq_org_invoice_client_uuid'),
        ),
    ]
