# Generated by Django 5.2.17 on 2026-08-30 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('organisation', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nom')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux %')),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
            options={
                'ordering': ['rate'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nom')),
                ('symbol', models.CharField(max_length=12, verbose_name='Symbole')),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organisation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, verbose_name='Référence')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='Code-barres')),
                ('name', models.CharField(max_length=200, verbose_name='Désignation')),
                ('brand', models.CharField(blank=True, max_length=80, verbose_name='Marque')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat")),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de vente')),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name="Seuil d'alerte")),
                ('location', models.CharField(blank=True, max_length=80, verbose_name='Emplacement')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='catalog.category')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='catalog.taxrate')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='catalog.unit')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organisation', 'sku')},
            },
        ),
    ]
